console.log("avanzar");
console.log("quitar 1");
console.log("avanzar");
console.log("quitar 1");
console.log("avanzar");
console.log("quitar 1");
console.log("avanzar");
console.log("quitar 1");
console.log("girar izquierda");
console.log("avanzar");
console.log("quitar 1");
console.log("avanzar");
console.log("quitar 1");
console.log("avanzar");
console.log("quitar 1");
console.log("avanzar");
console.log("quitar 1");
console.log("avanzar");
console.log("quitar 1");
